name: Update AUTHORS
on:
  push:
    branches:
      - br-*
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - name: Appr
        run: |
          echo "app-name: "
          echo "image-version: "
         
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create PR
        run: |
            gh pr create --base main --head new_branch -l "auto-merge" --title "Bump hash versi on environment" --body ""
 
