name: Update AUTHORS
on:
  push:
    branches:
      - br-*
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.PAT }}
          pull-request-number: 1
