name: Update AUTHORS
on:
  push:
    branches:
      - br-*
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - name: Appr
        run: |
          echo "app-name: "
          echo "image-version: "
         
      - name: Checkout repository
        uses: actions/checkout@v2

