name: Update AUTHORS
on:
  push:
    branches:
      - br-*
jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - name: Reset promotion branch
        run: |
          git fetch origin main:main
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: production-promotion
